src/FrontendBundle/Entity/Reclamation.php
<?php

namespace FrontendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Reclamation
 *
 * @ORM\Table(name="reclamation")
 * @ORM\Entity(repositoryClass="FrontendBundle\Repository\ReclamationRepository")
 */
class Reclamation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     *@ORM\Column(type="string" , length=255)
     */
    private $Titre;

    /**
     *@ORM\Column(type="string" , length=255)
     */
    private $Description;

    /**
     *@ORM\Column(type="string" , length=255)
     */
    private $etat;

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;
    }


    /**
     * @ORM\ManyToOne(targetEntity="AdminUserBundle\Entity\User")
     * @ORM\JoinColumn (name="user_id", referencedColumnName="id")
     */
    private $User;
    /**
     *@ORM\Column(type="date" , length=255)
     */
    private $date;

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getTitre()
    {
        return $this->Titre;
    }

    /**
     * @param mixed $Titre
     */
    public function setTitre($Titre)
    {
        $this->Titre = $Titre;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * @param mixed $Description
     */
    public function setDescription($Description)
    {
        $this->Description = $Description;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->User;
    }

    /**
     * @param mixed $User
     */
    public function setUser($User)
    {
        $this->User = $User;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}

src/FrontendBundle/Controller/DefaultController.php
<?php

namespace FrontendBundle\Controller;

use AdminUserBundle\Entity\User;
use ClientBundle\Entity\Demande;
use FrontendBundle\Entity\Reclamation;
use FrontendBundle\Form\ReclamationType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use ServiceBundle\Entity\Service;
use OffreBundle\Form\OffreType;
use OffreBundle\Entity\Offre;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('FrontendBundle:Default:index.html.twig');
    }
    public function HomeAction()
    {
        $demandes = $this->getDoctrine()->getRepository(Demande::class)->findAll();
        return $this->render('@Frontend/Default/Home.html.twig', array('demandes'=>$demandes));
    }
    public function ContacterAction(Request $request , $id)
    {

        $offre = new Offre();
        $form = $this->createForm(OffreType::class, $offre);
        $form = $form->handleRequest($request);
        $offre->setUser($this->getUser());
        $em = $this->getDoctrine()->getManager();
        $demande = $em->getRepository(Demande::class)->find($id);
         $client = $em->getRepository(User::class)->find($demande->getIdClient());
        $service = $em->getRepository(Service::class)->find($demande->getCategorie());
        if ($form->isSubmitted()){

            $offre->setDateAjout( new \DateTime('now'));
            $offre->setClient($client);
            $em->persist($offre);
            $em->flush();

            return $this->redirectToRoute("fixit_homepage");

        }
        return $this->render('@Frontend/Default/AddOffreClient.html.twig', array(
            'form'   => $form->createView(), 'client'=>$client , 'service' =>$service
        ));

    }

    public function OffresAction()
    {
        $user = $this->getUser();
        $user->getId();
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository('OffreBundle:Offre')->createQueryBuilder('d')->where('d.User =:id')
            ->setParameter('id',$user)->getQuery();
        $offres = $qb->getResult();
        $services = $this->getDoctrine()->getRepository(Service::class)->findAll();
        return $this->render('@Frontend/Default/MesOffres.html.twig', array('services'=>$services ,'offres' =>$offres));
    }
    public function servicesAction()
    {
        $user = $this->getUser();
        $user->getId();
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository('ServiceBundle:Service')->createQueryBuilder('d')->where('d.User =:id')
            ->setParameter('id',$user)->getQuery();
        $services = $qb->getResult();
        return $this->render('@Frontend/Default/MesServices.html.twig', array('services'=>$services ));
    }

    public function aboutusAction()
    {
        return $this->render('@Frontend/Default/aboutus.html.twig');
    }

    public function contactusAction(Request $request)
    {
        //return $this->render('@Frontend/Default/contactus.html.twig');
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form = $form->handleRequest($request);

        if ($form->isSubmitted()){
            $reclamation->setDate( new \DateTime('now'));
            $reclamation->setUser($this->getUser());
            $reclamation->setEtat("unread");
            $em = $this->getDoctrine()->getManager();
            $em->persist($reclamation);
            $em->flush();

            return $this->redirectToRoute("fixit_homepage");

        }
        return $this->render('@Frontend/Default/contactus.html.twig', array(
            'form'   => $form->createView(),
        ));
    }

    public function galleryAction()
    {
        return $this->render('@Frontend/Default/gallery.html.twig');
    }

    public function AddOffreAction(Request $request)
    {
        $offre = new Offre();
        $form = $this->createForm(OffreType::class, $offre);
        $form = $form->handleRequest($request);

        if ($form->isSubmitted()){
            $offre->setDateAjout( new \DateTime('now'));
            $offre->setUser($this->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($offre);
            $em->flush();

            return $this->redirectToRoute("fixit_MesOffres");

        }
        return $this->render('@Frontend/Default/AddOffre.html.twig', array(
            'form'   => $form->createView(),
        ));
       // return $this->render('@Frontend/Default/AddOffre.html.twig');
    }
    public function profilAction()
    {
        return $this->render('@Frontend/Default/profil.html.twig');
    }
    public function profilImprimerAction()
    {
        $snappy = $this->get("knp_snappy.pdf");
        $html = $this->renderView('@Frontend/Default/profil.html.twig');
        $filename= "custom_pdf_from_twig";

        return new Response(
            $snappy->getOutputFromHtml($html,array(
                'lowquality' => false,
                'encoding' => 'utf-8',
            )),
            200,
            array(
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="'.$filename.'.pdf"'
            )
        );
    }

    public function AddServiceAction()
    {
        return $this->render('@Frontend/Default/AddService.html.twig');
    }

    public function SuppOffreAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $modele= $em->getRepository(Offre::class)->find($id);

        $em->remove($modele);
        $em->flush();

        return $this->redirectToRoute("fixit_MesOffres");
    }

    public function ModifierOffreAction($id ,  Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $offre = $em->getRepository(Offre::class)->find($id);

        $form = $this->createForm(OffreType::class, $offre);
        $form->setData($offre);
        $form = $form->handleRequest($request);

        if ($form->isValid()) {
            $em->persist($offre);
            $em->flush();
            return $this->redirectToRoute("fixit_MesOffres");
        }
        return $this->render('@Frontend/Default/ModifierOffre.html.twig', array('form' => $form->createView()));
    }

}

src/FrontendBundle/Resources/views/Default/Home.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block header %}
    {{ parent() }}
{% endblock %}
{% block content %}
    {{ parent() }}
<body style="">
    <!-- Page Wrap ===========================================-->
    <div id="wrap">



        <!--======= HEADER =========-->

        <!--======= BANNER =========-->
        <div id="banner">
            <div class="flex-banner">
                <ul class="slides">
                    <li class="flex-active-slide" style="width: 100%; float: left; margin-right: -100%; position: relative; display: block; z-index: 2; opacity: 1;"> <img src="{{ asset('images/slide-1.jpg') }}" alt="" draggable="false">

                        <!--======= BANNER INNER =========-->
                        <div class="banner-up">
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-5">

                                        <!--======= BANNER FORM =========-->
                                        <div class="bnr-form">
                                            <h3>Quick service request</h3>
                                            <h6>24 housrs service available!</h6>
                                            <!--<div id="banner_message" class="success-msg"> <i class="fa fa-paper-plane-o"></i>Thank You. Your Message has been Submitted</div>-->
                                            <form role="form" id="banner_form" method="post" onsubmit="return false">
                                                <ul class="row">
                                                    <li class="col-sm-6">
                                                        <input type="text" name="name" id="name" placeholder="Name" required="">
                                                    </li>
                                                    <li class="col-sm-6">
                                                        <input type="text" name="phone" id="phone" placeholder="PHONE" required="">
                                                    </li>
                                                    <li class="col-sm-12">
                                                        <input type="text" name="email" id="email" placeholder="email" required="">
                                                    </li>
                                                    <li class="col-sm-12">
                                                        <textarea name="msgform" id="msgform" rows="5" placeholder="Description of work or services needed"></textarea>
                                                    </li>
                                                    <li class="col-sm-12">
                                                        <button type="submit" value="submit" class="btn" id="btn_submit" onclick="bannerProceed();">SUBMIT</button>
                                                    </li>
                                                </ul>
                                            </form>
                                        </div>
                                    </div>

                                    <!--======= BANNER IMAGES =========-->
                                    <div class="col-sm-7">
                                        <section> <img class="img-responsive pull-right" src="{{ asset('images/slide-img-1.png') }}" alt="" draggable="false"> </section>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: block; z-index: 1; opacity: 0;" class=""> <img src="{{ asset('images/slide-2.jpg') }}" alt="" draggable="false">

                        <!--======= BANNER INNER =========-->
                        <div class="banner-up">
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-5">
                                        <section> <img class="img-responsive pull-left" src="{{ asset('images/slide-img-2.png') }}" alt="" draggable="false"> </section>
                                    </div>
                                    <div class="col-sm-7">
                                        <div class="text-sec">
                                            <section>
                                                <h1>just call <span>+61 (123) 456 789</span></h1>
                                            </section>
                                            <section>
                                                <h1>we are always  ready to service</h1>
                                            </section>
                                            <a href="#." class="btn btn-1">get quote</a><a href="#." class="btn">about us</a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <ol class="flex-control-nav flex-control-paging"><li><a class="flex-active">1</a></li><li><a class="">2</a></li></ol><ul class="flex-direction-nav"><li><a class="flex-prev" href="#">Previous</a></li><li><a class="flex-next" href="#">Next</a></li></ul></div>
        </div>

        <li class="col-sm-8 " style="margin-left: 200px">
        {% for i in demandes %}
            <div class="admin-info">

                <ul class="row">
                    <li class="col-xs-2 no-padding"><img class="img-responsive"
                                                         src="{{ asset('images/team-1.jpg') }}"
                                                         alt=""></li>
                    <li class="col-xs-10">
                        <h5 class="text-uppercase no-margin">
                            {{ i.categorie.nom }}
                            : {{ i.budget }} DT
                        </h5>
                        <br>

                        <textarea cols="75" rows="3"
                                  style="padding:5px ;border-color: #448aff; border-radius: 5px ;resize:none"
                                  readonly>{{ i.description }}</textarea>

                        <a class="btn btn-default btn-sm"
                           href="{{ path('Contacter' , {id : i.id }) }}">
                            <i class="fa fa-edit"></i> Contacter !
                        </a>
                        <span style="margin-left: 220px"><i
                                    class="fa fa-calendar "></i> {{ i.date | date("m/d/Y") }} </span>
                    </li>
                </ul>

            </div>
        {% endfor %}
        </li>


        <!--======= CLIENTS FEEDBACK =========-->
        <section class="clients">
            <div class="container">

                <!--======= TITTLE =========-->
                <div class="tittle">
                    <h2>feedback from clients</h2>
                </div>
                <ul class="row">

                    <!--======= CLIENTS WORD =========-->
                    <li class="col-md-4">
                        <div class="avatar"> <img src="{{ asset('images/avatar-1.jpg')}}" alt=""> </div>
                        <div class="clients-in">
                            <p>Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae qicknit vitae dicta sunt explicabo. </p>
                            <h6>Jenny Nair -<span> Home Owner</span></h6>
                        </div>
                    </li>

                    <!--======= CLIENTS WORD =========-->
                    <li class="col-md-4">
                        <div class="avatar"> <img src="{{ asset('images/avatar-2.jpg')}}" alt=""> </div>
                        <div class="clients-in">
                            <p>Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae qicknit vitae dicta sunt explicabo. </p>
                            <h6>Jenny Nair -<span> Home Owner</span></h6>
                        </div>
                    </li>

                    <!--======= CLIENTS WORD =========-->
                    <li class="col-md-4">
                        <div class="avatar"> <img src="{{ asset('images/avatar-3.jpg')}}" alt=""> </div>
                        <div class="clients-in">
                            <p>Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae qicknit vitae dicta sunt explicabo. </p>
                            <h6>Jenny Nair -<span> Home Owner</span></h6>
                        </div>
                    </li>
                </ul>
            </div>
        </section>



        <!--======= FOOTER =========-->

    </div>
    <script src="{{ asset('js/jquery-1.11.0.min.js')}}"></script>
    <script src="{{ asset('js/wow.min.js')}}"></script>
    <script src="{{ asset('js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('js/jquery.stellar.js')}}"></script>
    <script src="{{ asset('js/jquery.isotope.min.js')}}"></script>
    <script src="{{ asset('js/jquery.flexslider-min.js')}}"></script>
    <script src="{{ asset('js/counter.js')}}"></script>
    <script src="{{ asset('js/owl.carousel.min.js')}}"></script>
    <script src="{{ asset('js/jquery.sticky.js')}}"></script>
    <script src="{{ asset('js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{ asset('js/own-menu.js')}}"></script>
    <script src="{{ asset('js/main.js')}}"></script>
    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        // Next/previous controls
        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        // Thumbnail image controls
        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) {slideIndex = 1}
            if (n < 1) {slideIndex = slides.length}
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex-1].style.display = "block";
            dots[slideIndex-1].className += " active";
        }

    </script>
    </body>
{% endblock %}

src/FrontendBundle/Resources/views/Default/index.html.twig
Hello !

src/FrontendBundle/Resources/views/Default/profil.html.twig
{% extends 'baseFrontendClient.html.twig' %}
{% block header %}
    {{ parent() }}
{% endblock %}
{% block steelsheet %}
    {{ parent() }}
    <link href="{{ absolute_url(asset('css/styleclient.css') )}}" rel="stylesheet" type="text/css">
    <link href="{{ absolute_url(asset('css/bootstrapclient.css')) }}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}

    <section class="profile_area">
        <div class="container">
            <div class="profile_inner " style="margin-top: 30px ; margin-bottom: 80px">
                <a href="{{ path('profilImprimer') }}">
                <button  class="btn" style="margin-left: 900px ; margin-top: 50px ;
                    width: 180px ; height: 70px ; background-color: #ffc107;
                    color: #ffffff; font-size: small">
                    Imprimer
                </button>
                </a>
                <div class="row">
                    <div class="col-lg-5">
                        <img class="img-fluid" src="{{ absolute_url(asset('images/personal.jpg') )}}" alt="">
                    </div>
                    <div class="col-lg-7">
                        <div class="personal_text" style="margin-top: 20px">
                            <h6>Hello Everybody, i am</h6>
                            <h3>Donald McKinney</h3>
                            <h4>Junior UI/UX Developer</h4>
                            <p>You will begin to realise why this exercise is called the Dickens Pattern (with reference to the ghost showing Scrooge some different futures)</p>
                            <ul class="list basic_info">
                                <li><a href="#" ><i  ><i class="fa fa-calendar"></i></i> 31st December, 1992</a></li>
                                <li><a href="#"><i class="fa fa-phone"></i>44 (012) 6954 783</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> businessplan@donald</a></li>
                                <li><a href="#"><i class="fa fa-home"></i> Santa monica bullevard</a></li>
                            </ul>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block footer %}
{% endblock %}

src/FrontendBundle/Resources/views/Default/services2.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block header %}
    {{ parent() }}
{% endblock %}
{% block content %}
    {{ parent() }}

    <body style="">

    <!-- Page Wrap ===========================================-->
    <div id="wrap">


        <!--======= BLOG =========-->
        <section class="blog">
            <div class="container">
                <h4 class="text-uppercase margin-t-20">Mes Offres</h4>

                <ul class="row">
                    <li class="col-sm-8">


                        <!--======= ADMIN INFO =========-->
                        {% for i in services %}
                            <div class="admin-info">

                                <ul class="row" >
                                    <li class="col-xs-2 no-padding"><img class="img-responsive"
                                                                         src="{{ asset('images/team-1.jpg') }}"
                                                                         alt=""></li>
                                    <li class="col-xs-10">
                                        <h5 class="text-uppercase no-margin"></h5>
                                        <br>
                                        <p>{{ i.titre }}</p>
                                        <p>{{ i.budget }}</p>
                                        <p>{{ i.description }}</p>

                                        <div class="btn-group">
                                            <a class="btn btn-default btn-sm" href="{{ path('offre_show', {id: i.id}) }}">
                                                <i class="fa fa-file-o"></i> {{ 'show'|trans({}, 'admin') }}
                                            </a>
                                            <a class="btn btn-default btn-sm" href="{{ path('offre_edit', {id: i.id}) }}">
                                                <i class="fa fa-edit"></i> {{ 'edit'|trans({}, 'admin') }}
                                            </a>
                                        </div>



                                    </li>
                                </ul>

                            </div>
                        {% endfor %}
                    </li>
                    <!--======= SIDE BAR =========-->
                    <li class="col-sm-4" >
                        <div class="blog-side-bar" >


                            <!--=======  RECENT POST =========-->
                            <h5>offres récenement ajoutés </h5>
                            <div  class="tw-widgets">
                                <ul >

                                    <!--=======  RECENT POST =========-->
                                    <li >
                                        <ul class="wid-in">
                                            <li><a href="#."><img class="img-responsive"
                                                                  src="{{ asset('images/gal-img-3.jpg') }}"
                                                                  alt=""></a></li>
                                            <li>
                                                <div class="img-side"></div>
                                                <a href="#.">Beritatis et Quasi Arcteco veatae Vitae</a> <span><i
                                                            class="fa fa-calendar"></i>Jan 12, 2015 </span></li>
                                        </ul>
                                    </li>

                                    <!--=======  RECENT POST =========-->
                                    <li>
                                        <ul class="wid-in">
                                            <li><a href="#."><img class="img-responsive"
                                                                  src="{{ asset('images/gal-img-2.jpg') }}"
                                                                  alt=""></a></li>
                                            <li>
                                                <div class="img-side"></div>
                                                <a href="#.">Seritatis et Quasi Arcteco veatae Vitae</a> <span><i
                                                            class="fa fa-calendar"></i>Jan 12, 2015 </span></li>
                                        </ul>
                                    </li>

                                    <!--=======  RECENT POST =========-->
                                    <li>
                                        <ul class="wid-in">
                                            <li><a href="#."><img class="img-responsive"
                                                                  src="{{ asset('images/gal-img-3.jpg') }}"
                                                                  alt=""></a></li>
                                            <li>
                                                <div class="img-side"></div>
                                                <a href="#.">Seritatis et Quasi Arcteco veatae Vitae</a> <span><i
                                                            class="fa fa-calendar"></i>Jan 12, 2015 </span></li>
                                        </ul>
                                    </li>

                                    <!--=======  RECENT POST =========-->
                                    <li>
                                        <ul class="wid-in">
                                            <li><a href="#."><img class="img-responsive"
                                                                  src="{{ asset('images/gal-img-2.jpg') }}"
                                                                  alt=""></a></li>
                                            <li>
                                                <div class="img-side"></div>
                                                <a href="#.">Seritatis et Quasi Arcteco veatae Vitae</a> <span><i
                                                            class="fa fa-calendar"></i>Jan 12, 2015 </span></li>
                                        </ul>
                                    </li>

                                    <!--=======  RECENT POST =========-->
                                    <li>
                                        <ul class="wid-in">
                                            <li><a href="#."><img class="img-responsive"
                                                                  src="{{ asset('images/gal-img-4.jpg') }}"
                                                                  alt=""></a></li>
                                            <li>
                                                <div class="img-side"></div>
                                                <a href="#.">Seritatis et Quasi Arcteco veatae Vitae</a> <span><i
                                                            class="fa fa-calendar"></i>Jan 12, 2015 </span></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>


                        </div>
                    </li>
                </ul>

            </div>
        </section>


    </div>


    <script src="{{ asset('js/jquery-1.11.0.min.js') }}"></script>
    <script src="{{ asset('js/wow.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/jquery.stellar.js') }}"></script>
    <script src="{{ asset('js/jquery.isotope.min.js') }}"></script>
    <script src="{{ asset('js/jquery.flexslider-min.js') }}"></script>
    <script src="{{ asset('js/counter.js') }}"></script>
    <script src="{{ asset('js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('js/jquery.sticky.js') }}"></script>
    <script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('js/own-menu.js') }}"></script>
    <script src="{{ asset('js/main.js') }}"></script>
    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        // Next/previous controls
        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        // Thumbnail image controls
        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) {
                slideIndex = 1
            }
            if (n < 1) {
                slideIndex = slides.length
            }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }

    </script>
    </body>
{% endblock %}